### ISSUE TITLE
Error when tags contains a comma. 

### ISSUE THREAD

**Issue by manere** [peerigon/angular-expressions#11]
Hello, 

first of all, thank you for providing us with this and Docxtemplater.

I think I found a bug. I have placeholders that look like this {case,contact,name}. 
I have a good amount of limitations and requirements and with this I don't want to go for a/can't go for a {case.contact.name} structure like you did in your first example. 
https://docxtemplater.readthedocs.io/en/latest/angular_parse.html

Here are my specs: 
- Version of Docxtemplater: v3.15.0
- Version of angular-expressions. 1.0 
- Used docxtemplater-modules : none
- Runner : Google Chrome (latest Version)

Code is `var angularParser = function(tag) {
      if (tag === ".") {
        return {
          get: function(s) {
            return s;
          }
        };
      }
      const expr = angularExpressions.compile(tag);
      return {
        get: function(scope, context) {
          let obj = {};
          const scopeList = context.scopeList;
          const num = context.num;
          for (let j = 0, len = num + 1; j < len; j++) {
            obj = new lodashMerger(obj, scopeList[j]);
          }
          return expr(scope, obj);
        }
      };
    };`

The error happens at the `const expr = angularExpressions.compile(tag);`
Thats the error message:
![ErrorAngularParser](https://user-images.githubusercontent.com/54940791/69550008-90fb7400-0f9a-11ea-86c3-f2cc104cf887.PNG)

I hope you can fix it (if it is a bug) or correct me if I am wrong.

**Comment by edi9999** [comment]
Hello @manere , Sorry for the late reply, what exactly would you like to achieve with : 

```
{case,contact,name}
```

This is indeed an invalid expression, what would you like to achieve ?

Is your data like this : 

```
{
   "case": {
      "contact": {
          "name": "John doe"
      }
   }
}
```

In that case, you should indeed write `{case.contact.name}` instead.

**Comment by manere** [comment]
@edi9999 We have Tags like {Contact.Name} and they work perfectly fine. We needed the {case,contact,name} to query data that then would NOT show up inside the docx File. 
 Though through trial and error, I found out that $ does not throw an Error so our query Tags look like this: {Contact$Cases$Name}. 


This solution works perfectly fine for my needs. My goal with this post was to only to point out that you are running into an error, when ',' are used. 


Otherwise thank you again for the libraries. Performance is mind-blowing honestly.

**Comment by edi9999** [comment]
Ok, I got it, good if it works like this then.

Also, have you seen the patch for a high vulnerability in this package ? You should upgrade to angular-expressions@1.0.1

See https://github.com/open-xml-templating/docxtemplater/issues/488 for more details.

**Comment by manere** [comment]
@edi9999 Great. Will upgrade.
