### ISSUE TITLE
Issue when evaluating expressions containing Object methods (ie. String.toUpperCase())

### ISSUE THREAD

**Issue by Elyanas** [peerigon/angular-expressions#18]
Hello,

I just migrated to the last version of angular-expressions after seeing the library had security issues on versions < 1.0.1

My problem is that it's now impossible to call native object functions like String.toUpperCase().

https://github.com/peerigon/angular-expressions/blob/b7a4aa4489359b45ed65af9032dec94cf837ddb6/test/main.test.js#L464

From the readme : 

> As an example, consider the following Angular expression:
> 
> {}.toString.constructor(alert("evil JS code"))
> 
> We want to prevent this type of access. For the sake of performance, during the lexing phase we disallow any "dotted" access to any member named "constructor".

It seems you have now limited access to ALL prototype members, not just "constructor". Is it intended ? AngularJs has no problem evaluating those type of expressions so it seems strange that this library does not have the same behavior.

I hope I'm not missing anything... If you could enlighten me it would be greatly appreciated !

**Comment by edi9999** [comment]
See this : https://docs.angularjs.org/guide/security#angularjs-templates-and-expressions

AngularJS never intended to make the expressions safe, but I think for many usecases, the whole point of using this expression engine is to let untrusted users write a bit of code (for example in a templating engine, or to let users write some logic).

**Comment by edi9999** [comment]
I would in your case, rather define filters for the few things you would like to allow, for example : 

```
expressions.filters.uppercase = function(input) {
   return input.toUpperCase();
}
```

And in your template, write `{input | uppercase}`

**Comment by Elyanas** [comment]
I wasn't questioning the intention behind it. It's just that for my use case I need to replicate AngularJS's own client side evaluation of the same expression (which could contain a call to native function). I am aware of the security issues though.

I guess i was just under the impression that the library was intended to mimic exactly AngularJS's own evaluation of expressions but it seems you intend this library to stand on it's own, which I understand.

Thanks anyway !
