### ISSUE TITLE
A condition with .indexOf() in it

### ISSUE THREAD

**Issue by marmite22** [peerigon/angular-expressions#20]
I'm porting an Angular app to React.  I have a conditions saved as a string that were created by users. For example to test if a something begins with a

"foo.indexOf('a') === 0"

Is there a way to have that functionality work with this library as it does in Angular? What I'm trying to avoid is having to batch update all the existing saved conditions.

Thanks in advance.

**Comment by edi9999** [comment]
Hello, I've disabled prototype functions such as indexOf for security reasons (it allows persons that have control over the expression to run arbitrary code). You could use version 1.0.0 which is an old version which still had support for indexOf.

On the current version (1.1.1), you can define an explicit filter to allow you to write it like this for example : 

"(foo | indexOf:'a') === 0"

by writing the following : 

```
expressions.filters.indexOf = (input, search) => {
   return input.indexOf(search)
};
```

You could also even have a startsWith filter like this : 

"foo | startsWith:'a'"

```
expressions.filters.startsWith = (input, search) => {
   return input.indexOf(search) === 0;
};
```

**Comment by marmite22** [comment]
Thanks for the speedy reply. I'll see what I can do with the filters. That should be able to handle what I need (although I might have to regex user's expressions into the new filter format.
