### ISSUE TITLE
assign missing from type def of EvaluatorFunc

### ISSUE THREAD

**Issue by kevinfairclough** [peerigon/angular-expressions#40]
![image](https://github.com/peerigon/angular-expressions/assets/2623164/0a25d93b-bbdc-421a-84ee-9cb056d9a7f8)

Fix could be this:
```
type EvaluatorFunc = {
  (scope?: any, context?: any): any;
  ast: any;
  assign: (scope: any, value: any) => any;
};
```

**Comment by edi9999** [comment]
Fixed in version 1.1.9 which I just released
